### ISSUE TITLE
Question, how do I add or query points in octree?

### ISSUE THREAD

**Issue by trsh** [rusty-fast-solvers/rusty-tree#1]

**Comment by skailasa** [comment]
Hi @trsh, when you asked this question this repo was largely a placeholder. Having finally released the first version, you should be able to do this now from both Rust, as well as using our Python bindings distributed via conda.

For installation instructions, checkout the updated readme. For usage, there are a some trivial examples in the project's wiki.

**Comment by trsh** [comment]
@skailasa would be nice to have a longer example showcasing all capabilities. Or documentation.

**Comment by skailasa** [comment]
At the moment, these are more or less all the capabilites. You can create distributed trees from a set of distributed data points. There are Morton encoding functions under the hood, but those aren't really a feature of this library's API.  Future releases will make this more usable with MPI capable IO, support for different data formats, plotting etc. But the core API - to generate a distributed tree - will largely be the same. 

What would you like to know specifally?

**Comment by trsh** [comment]
I was looking for a OC solution where can also add, remove and update points or AABB's containers. However at this point I am not working on the project any more. So I will close this.
