### ISSUE TITLE
Error in encoding negative point data.

### ISSUE THREAD

**Issue by skailasa** [rusty-fast-solvers/rusty-tree#11]
Some error encoding/decoding points with negative coordinate values. Either in the method for box_coordinates. or elsewhere.

**Comment by skailasa** [comment]
Quite possible in Domain calculation

**Comment by skailasa** [comment]
Added a PR [here](https://github.com/rusty-fast-solvers/rusty-tree/pull/12), if either @tbetcke or @mscroggs wants to review?

I've also added branch protection to that specific repo, enforcing reviews before merging - something we should probably do to all repos before new developers join the project?

**Comment by tbetcke** [comment]
Merged into main.
